contentdir = "content"
layoutdir = "layouts"
publishdir = "docs"
builddrafts = true 
canonifyurls = true
baseurl = "/"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
theme = "hugo-envisioned"
googleAnalytics = "UA-159074441-1"
title = "Jacob Sowder"

[taxonomies]
  category = "categories" 
  group = "groups"
  series = "series"
  tag = "tags"

[params]
  subtitle = ""
  copyrightHolder = ""
  showPoweredBy = false
  showCopyright = false

# -----------------------------------------------------------------------
# Navigation menu 
# -----------------------------------------------------------------------
[[menu.nav]]
  name = "Email"
  weight = -100 
  identifier = "email"
  url = "mailto:jacobsowder@gmail.com?subject=Nice to meet you!"
  
[[menu.nav]]
  name = "Resume"
  weight = -100 
  identifier = "resume"
  url = "/resume.pdf"
  
[[menu.nav]]
  pre = "<i class='fa fa-github fa-lg'></i> "
  weight = -100 
  identifier = "github"
  url = "https://github.com/jsowder"
  
[[menu.nav]]
  pre = "<i class='fa fa-linkedin fa-lg'></i> "
  weight = -100 
  identifier = "linked-in"
  url = "https://www.linkedin.com/in/jacobsowder/"

# -----------------------------------------------------------------------
# Footer menu 
# -----------------------------------------------------------------------
[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-linkedin fa-2x'></i> "
  weight = -90 
  identifier = "linkedin"
  url = "https://www.linkedin.com/in/jacobsowder/"
[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-github fa-2x'></i> "
  weight = -100 
  identifier = "github"
  url = "https://github.com/jsowder"
